// This file is generated by the FlutterFire CLI.
//
// Run the following command from the project root AFTER linking your Firebase
// project to generate the real values:
//
//   flutterfire configure
//
// DO NOT commit real API keys to version control.
// See: https://firebase.flutter.dev/docs/cli/

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace the placeholder values below with the output of `flutterfire configure`.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'reconfigure using the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvW44wVY6wZ6UcFZoobOKibBoXJ_L_fA',
    appId: '1:472092949325:android:8d7e3454c788ffc62c5504',
    messagingSenderId: '472092949325',
    projectId: 'isg-chat-app',
    storageBucket: 'isg-chat-app.firebasestorage.app',
  );

  /// ⚠️  REPLACE with your Android Firebase config values.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdRlb9E7hASQHXmI3oK-j0o3KNPmr_Lc',
    appId: '1:472092949325:ios:e6adeb9f1983ba5c2c5504',
    messagingSenderId: '472092949325',
    projectId: 'isg-chat-app',
    storageBucket: 'isg-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.isgChatApp',
  );

  /// ⚠️  REPLACE with your iOS Firebase config values.
}
